# Notebook #1: Introduction to the Definitve Screening Design

In [1]:
import pandas as pd
import definitive_screening_design as dsd

In [2]:
# Generate a DSD with 5 numerical factors
df = dsd.generate(n_num=5)
df

Generating a Definitive Screening Design with 5 numerical and 0 categorical factors.

    X01  X02  X03  X04  X05
1   0.0  1.0  1.0  1.0  1.0
2   0.0 -1.0 -1.0 -1.0 -1.0
3   1.0  0.0 -1.0  1.0  1.0
4  -1.0  0.0  1.0 -1.0 -1.0
5   1.0 -1.0  0.0 -1.0  1.0
6  -1.0  1.0  0.0  1.0 -1.0
7   1.0  1.0 -1.0  0.0 -1.0
8  -1.0 -1.0  1.0  0.0  1.0
9   1.0  1.0  1.0 -1.0  0.0
10 -1.0 -1.0 -1.0  1.0  0.0
11  1.0 -1.0  1.0  1.0 -1.0
12 -1.0  1.0 -1.0 -1.0  1.0
13  0.0  0.0  0.0  0.0  0.0

In [3]:
# Generate a DSD with 5 numerical factors and 2 categorical factors
df = dsd.generate(n_num=5, n_cat=2)
df

Generating a Definitive Screening Design with 5 numerical and 2 categorical factors.

    X01  X02  X03  X04  X05 C01 C02
1   0.0  1.0  1.0  1.0  1.0   B   B
2   0.0 -1.0 -1.0 -1.0 -1.0   A   A
3   1.0  0.0 -1.0 -1.0  1.0   A   B
4  -1.0  0.0  1.0  1.0 -1.0   B   A
5   1.0  1.0  0.0 -1.0 -1.0   B   A
6  -1.0 -1.0  0.0  1.0  1.0   A   B
7   1.0  1.0  1.0  0.0 -1.0   A   B
8  -1.0 -1.0 -1.0  0.0  1.0   B   A
9   1.0 -1.0  1.0  1.0  0.0   A   A
10 -1.0  1.0 -1.0 -1.0  0.0   B   B
11  1.0  1.0 -1.0  1.0  1.0   B   A
12 -1.0 -1.0  1.0 -1.0 -1.0   A   B
13  1.0 -1.0  1.0 -1.0  1.0   B   B
14 -1.0  1.0 -1.0  1.0 -1.0   A   A
15  1.0 -1.0 -1.0  1.0 -1.0   B   B
16 -1.0  1.0  1.0 -1.0  1.0   A   A
17  0.0  0.0  0.0  0.0  0.0   A   A
18  0.0  0.0  0.0  0.0  0.0   B   B

In [4]:
# Add 2 fake_factors to augment the design with 4 trials
df = dsd.generate(n_num=5, n_cat=2, n_fake_factors=2)
df

Generating a Definitive Screening Design with 5 numerical and 2 categorical factors.

    X01  X02  X03  X04  X05 C01 C02
1   0.0  1.0  1.0  1.0  1.0   B   B
2   0.0 -1.0 -1.0 -1.0 -1.0   A   A
3   1.0  0.0 -1.0 -1.0 -1.0   B   B
4  -1.0  0.0  1.0  1.0  1.0   A   A
5   1.0 -1.0  0.0 -1.0  1.0   A   B
6  -1.0  1.0  0.0  1.0 -1.0   B   A
7   1.0 -1.0 -1.0  0.0  1.0   B   A
8  -1.0  1.0  1.0  0.0 -1.0   A   B
9   1.0 -1.0  1.0  1.0  0.0   B   A
10 -1.0  1.0 -1.0 -1.0  0.0   A   B
11  1.0 -1.0  1.0  1.0 -1.0   A   B
12 -1.0  1.0 -1.0 -1.0  1.0   B   A
13  1.0  1.0 -1.0  1.0 -1.0   A   A
14  1.0 -1.0  1.0 -1.0  1.0   B   B
15  1.0  1.0 -1.0  1.0  1.0   B   B
16 -1.0 -1.0  1.0 -1.0 -1.0   A   A
17  1.0  1.0  1.0 -1.0 -1.0   B   B
18 -1.0 -1.0 -1.0  1.0  1.0   A   A
19  1.0  1.0  1.0 -1.0  1.0   A   A
20 -1.0 -1.0 -1.0  1.0 -1.0   B   B
21  0.0  0.0  0.0  0.0  0.0   A   A
22  0.0  0.0  0.0  0.0  0.0   B   B

> NOTE: 2 fake factors will augment the DSD with 4 trials, 4 fake factors will add 8 trials, 6 will add 12 trials, and so on.

In [5]:
# Use a factors_dict to generate the design
factors_dict = {
    "Temperature": [30, 60],          # Numerical factor
    "Pressure": [1, 10],              # Numbrical factor
    "Solvent": ["Solv-A", "Solv-B"],  # Categorical 2-levels factor
    "Vessel#": ["1", "2"],            # Note that by writing the numbers as string, you treat the factors as 2-levels categorical
    "Stirring_speed": [500, 700]      # Numerical factor
}
df = dsd.generate(factors_dict=factors_dict)
df

Generating a Definitive Screening Design from factors dictionary: 3 numerical and 2 categorical.

    Temperature  Pressure Solvent Vessel#  Stirring_speed
1          45.0      10.0  Solv-B       2           700.0
2          45.0       1.0  Solv-A       1           500.0
3          60.0       5.5  Solv-B       1           500.0
4          30.0       5.5  Solv-A       2           700.0
5          60.0       1.0  Solv-B       2           600.0
6          30.0      10.0  Solv-A       1           600.0
7          60.0      10.0  Solv-A       2           500.0
8          30.0       1.0  Solv-B       1           700.0
9          60.0      10.0  Solv-B       1           700.0
10         30.0       1.0  Solv-A       2           500.0
11         60.0       1.0  Solv-A       2           700.0
12         30.0      10.0  Solv-B       1           500.0
13         45.0       5.5  Solv-A       1           600.0
14         45.0       5.5  Solv-B       2           600.0

## Check the size of the DSD when using a different combination of `n_num` and `n_cat`
The number of trials in a definitive screening design (typically ca. 2N+1) will be compared with a full-factorial DOE having 3 levels for each numerical factor and 2 levels for the categorical factors.

In [6]:
df_list = []
for n_cat in range(0, 12):
 for n_num in range(0, 12):
        if not n_num and not n_cat:
            continue
        dsd_df = dsd.generate(
            n_num, 
            n_cat, 
            factors_dict=None, # No need for inputing a factors_dict in this example
            min_13=False,      # Default: True. `True` will add fake factors in small design, to have always a minimum of 13 trials.
            n_fake_factors=0,  # No need for fake factors in this example   
            verbose=False      # Default: True. `False` will suppress verrbosity
        )
        df_list.append({
            "n_num": n_num,
            "n_cat": n_cat,
            "n_tot": n_num+n_cat,
            "DSd length": len(dsd_df),
            "2*n_tot+1": 2*(n_num+n_cat)+1,
            "3^n_num * 2^n_cat": 3**n_num * 2**n_cat,

        })

pd.set_option('display.max_rows', 500)
pd.DataFrame(df_list)

     n_num  n_cat  n_tot  DSd length  2*n_tot+1  3^n_num * 2^n_cat
0        1      0      1           9          3                  3
1        2      0      2           9          5                  9
2        3      0      3           9          7                 27
3        4      0      4           9          9                 81
4        5      0      5          13         11                243
5        6      0      6          13         13                729
6        7      0      7          17         15               2187
7        8      0      8          17         17               6561
8        9      0      9          21         19              19683
9       10      0     10          21         21              59049
10      11      0     11          25         23             177147
11       0      1      1          10          3                  2
12       1      1      2          10          5                  6
13       2      1      3          10          7                 18
14       3      1      4          10          9                 54
15       4      1      5          14         11                162
16       5      1      6          14         13                486
17       6      1      7          18         15               1458
18       7      1      8          18         17               4374
19       8      1      9          22         19              13122
20       9      1     10          22         21              39366
21      10      1     11          26         23             118098
22      11      1     12          26         25             354294
23       0      2      2          10          5                  4
24       1      2      3          10          7                 12
25       2      2      4          10          9                 36
26       3      2      5          14         11                108
27       4      2      6          14         13                324
28       5      2      7          18         15                972
29       6      2      8          18         17               2916
30       7      2      9          22         19               8748
31       8      2     10          22         21              26244
32       9      2     11          26         23              78732
33      10      2     12          26         25             236196
34      11      2     13          30         27             708588
35       0      3      3          10          7                  8
36       1      3      4          10          9                 24
37       2      3      5          14         11                 72
38       3      3      6          14         13                216
39       4      3      7          18         15                648
40       5      3      8          18         17               1944
41       6      3      9          22         19               5832
42       7      3     10          22         21              17496
43       8      3     11          26         23              52488
44       9      3     12          26         25             157464
45      10      3     13          30         27             472392
46      11      3     14          30         29            1417176
47       0      4      4          10          9                 16
48       1      4      5          14         11                 48
49       2      4      6          14         13                144
50       3      4      7          18         15                432
51       4      4      8          18         17               1296
52       5      4      9          22         19               3888
53       6      4     10          22         21              11664
54       7      4     11          26         23              34992
55       8      4     12          26         25             104976
56       9      4     13          30         27             314928
57      10      4     14          30         29             944784
58      11      4     15          34         31            2834352
59       0      5      5          14         11                 32
60       1      5      6          14         13                 96
61       2      5      7          18         15                288
62       3      5      8          18         17                864
63       4      5      9          22         19               2592
64       5      5     10          22         21               7776
65       6      5     11          26         23              23328
66       7      5     12          26         25              69984
67       8      5     13          30         27             209952
68       9      5     14          30         29             629856
69      10      5     15          34         31            1889568
70      11      5     16          34         33            5668704
71       0      6      6          14         13                 64
72       1      6      7          18         15                192
73       2      6      8          18         17                576
74       3      6      9          22         19               1728
75       4      6     10          22         21               5184
76       5      6     11          26         23              15552
77       6      6     12          26         25              46656
78       7      6     13          30         27             139968
79       8      6     14          30         29             419904
80       9      6     15          34         31            1259712
81      10      6     16          34         33            3779136
82      11      6     17          38         35           11337408
83       0      7      7          18         15                128
84       1      7      8          18         17                384
85       2      7      9          22         19               1152
86       3      7     10          22         21               3456
87       4      7     11          26         23              10368
88       5      7     12          26         25              31104
89       6      7     13          30         27              93312
90       7      7     14          30         29             279936
91       8      7     15          34         31             839808
92       9      7     16          34         33            2519424
93      10      7     17          38         35            7558272
94      11      7     18          38         37           22674816
95       0      8      8          18         17                256
96       1      8      9          22         19                768
97       2      8     10          22         21               2304
98       3      8     11          26         23               6912
99       4      8     12          26         25              20736
100      5      8     13          30         27              62208
101      6      8     14          30         29             186624
102      7      8     15          34         31             559872
103      8      8     16          34         33            1679616
104      9      8     17          38         35            5038848
105     10      8     18          38         37           15116544
106     11      8     19          42         39           45349632
107      0      9      9          22         19                512
108      1      9     10          22         21               1536
109      2      9     11          26         23               4608
110      3      9     12          26         25              13824
111      4      9     13          30         27              41472
112      5      9     14          30         29             124416
113      6      9     15          34         31             373248
114      7      9     16          34         33            1119744
115      8      9     17          38         35            3359232
116      9      9     18          38         37           10077696
117     10      9     19          42         39           30233088
118     11      9     20          42         41           90699264
119      0     10     10          22         21               1024
120      1     10     11          26         23               3072
121      2     10     12          26         25               9216
122      3     10     13          30         27              27648
123      4     10     14          30         29              82944
124      5     10     15          34         31             248832
125      6     10     16          34         33             746496
126      7     10     17          38         35            2239488
127      8     10     18          38         37            6718464
128      9     10     19          42         39           20155392
129     10     10     20          42         41           60466176
130     11     10     21          50         43          181398528
131      0     11     11          26         23               2048
132      1     11     12          26         25               6144
133      2     11     13          30         27              18432
134      3     11     14          30         29              55296
135      4     11     15          34         31             165888
136      5     11     16          34         33             497664
137      6     11     17          38         35            1492992
138      7     11     18          38         37            4478976
139      8     11     19          42         39           13436928
140      9     11     20          42         41           40310784
141     10     11     21          50         43          120932352
142     11     11     22          50         45          362797056